### ISSUE TITLE
bug in old world with ender io

### ISSUE THREAD

**Issue by ferreiraalex** [GregTechCEu/gregicality#595]
https://pastebin.com/JzU41L6u

**Comment by ferreiraalex** [comment]
[20:23:28] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.ClassCastException: gregicadditions.integrations.FECompat.GregicEnergyContainerWrapper cannot be cast to net.minecraftforge.energy.IEnergyStorage
	at crazypants.enderio.base.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:19) ~[PowerHandlerUtil.class:?]
	at crazypants.enderio.conduits.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:478) ~[PowerConduit.class:?]
	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:61) ~[PowerConduitNetwork.class:?]
	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:21) ~[PowerConduitNetwork.class:?]
	at crazypants.enderio.conduits.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:94) ~[AbstractConduitNetwork.class:?]
	at crazypants.enderio.conduits.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:67) ~[AbstractConduitNetwork.class:?]
	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.init(PowerConduitNetwork.java:35) ~[PowerConduitNetwork.class:?]
	at crazypants.enderio.base.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:66) ~[ConduitUtil.class:?]
	at crazypants.enderio.conduits.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:462) ~[AbstractConduit.class:?]
	at crazypants.enderio.conduits.conduit.AbstractConduit.updateEntity(AbstractConduit.java:397) ~[AbstractConduit.class:?]
	at crazypants.enderio.conduits.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:339) ~[TileConduitBundle.class:?]
	at com.enderio.core.common.TileEntityBase.update(TileEntityBase.java:49) ~[TileEntityBase.class:?]
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38) ~[McHooks.class:?]
	at net.minecraft.world.World.updateEntities(MixinWorldRedstone.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]

**Comment by ALongStringOfNumbers** [comment]
This should now be fixed with 5351c63
